[workspace]
members = ["flight-controller", "gcs", "plane-core"]
resolver = "3"

[workspace.dependencies]
postcard = "1.1.1"
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
bitflare = { git = "https://github.com/TroyNeubauer/bitflare.git", default-features = false }

[profile.release]
debug = 1
lto = "fat"
opt-level = 's'
